site_name: jetblack-markdown
site_description: A markdown extension for mkdocs.
site_dir: docs

docs_dir: documentation

repo_name: rob-blackbourn/jetblack-markdown
repo_url: https://github.com/rob-blackbourn/jetblack-markdown
edit_uri: ""

theme:
    name: 'material'

nav:
  - index.md
  - User Guide:
    - user-guide/config.md
    - user-guide/docstrings.md
    - user-guide/templates.md
  - API:
    - jetblack-autodoc: api/jetblack_autodoc.md
    - jetblack_markdown.autodoc: api/jetblack_markdown.md
    - jetblack_markdown.metadata: api/jetblack_metadata.md
  
markdown_extensions:
  - admonition
  - codehilite
  - jetblack_markdown.autodoc:
      class_from_init: true
      ignore_dunder: true
      ignore_private: true
      ignore_all: false
      ignore_inherited: false
      follow_module_tree: false
      prefer_docstring: true

extra_css:
    - css/custom.css
